### NumPy 

* Numpy is array-processing package.

### Installation Instructions

    pip install numpy
    conda install numpy
    

### Numpy method use for analysis

#### 1.  np.array()                   2.  np.arange()              3.  np.linspace()
#### 4.  np.random.rand()      5.  np.random.randn() 6.  np.random.randint()

### Array Attribute and method

#### 7.  .reshape()                   8.  .min()/.max()           9.  .argmin()         10.  .dtype  11. .shape

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. 

#### Numpy Arrays

NumPy arrays  are strictly 1-d arrays and matrices are 2-d.


#### Creating NumPy Arrays from list

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

There are lots of built-in ways to generate Arrays

#### arange

Return evenly spaced values within a given interval.

#### Syntax -:  np.arange(start, end, increament)

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones

Generate arrays of zeros or ones

#### Syntax -: np.zeros(no. of rows, no. of column)

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace
Return even spaced numbers over a specified interval.

#### Syntax -: np.linspace(start, end, total  number to generate)

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

#### eye

Creates an identity matrix

#### Syntax -: np.eye(size of matrix)

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random 

Numpy also has lots of ways to create random number arrays:

#### rand

Create an array of the given shape and  with
random samples from a uniform distribution.

#### Syntax -: np.random.rand(no. of rows, no of columns)

In [15]:
np.random.rand(2)

array([0.49928518, 0.13713662])

In [16]:
np.random.rand(5,5)

array([[0.15290474, 0.1498464 , 0.81194579, 0.3846395 , 0.91497935],
       [0.10938203, 0.4974264 , 0.36875224, 0.55610167, 0.51355564],
       [0.87160007, 0.00232131, 0.63743374, 0.6880401 , 0.57524589],
       [0.09640014, 0.33819815, 0.4576574 , 0.58001263, 0.42854932],
       [0.69563317, 0.21100247, 0.28745603, 0.00320812, 0.2724037 ]])

#### randn

Return a samples from the "standard normal" distribution.

#### Syntax -: np.random.randn(number of rows, number of column)

In [17]:
np.random.randn(2)

array([-0.60966929,  0.77173197])

In [18]:
np.random.randn(5,5)

array([[ 0.37003366,  0.25676155, -0.12801184, -1.45190215,  0.13412501],
       [-1.19577854, -0.78145926,  0.21423877, -1.39098207, -0.64646517],
       [-0.18052965, -0.04302679, -1.04795412,  1.11616743,  1.03971687],
       [-0.04485359,  0.70118028,  0.71662854,  1.60877714, -0.51263526],
       [ 0.41310633, -2.52083387,  1.71408037, -0.47489464, -0.84265982]])

#### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

#### Syntax -: np.rand.randint(start, end , total numbers to generate)

In [19]:
np.random.randint(1,100)

4

In [20]:
np.random.randint(1,100,10)

array([36, 55,  7,  5, 23,  2, 26, 89,  2, 69])

#### Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([22, 37, 31, 34, 13,  3, 23, 26, 42, 22])

#### Reshape

It is used to create new shape of array.

#### Syntax-: np.reshape(no of rows, no of column)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

##### max()    It is used to find the maximum term from the array.
##### min()    It is used to find the minimum term from the array.
##### argmax() It gives the index of max term in given array.
##### argmin() It gives the indewx of minterm from the given array.

In [25]:
ranarr

array([22, 37, 31, 34, 13,  3, 23, 26, 42, 22])

In [26]:
ranarr.max()

42

In [27]:
ranarr.argmax()

8

In [28]:
ranarr.min()

3

In [29]:
ranarr.argmin()

5

## Shape

### Shape is an attribute .

It is used to denote the size of an array.(row, column)

#### syntax -: array_name.shape()


In [30]:
arr.shape   

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

## dtype

### dtype is also the attributrites.

You can also grab the data type of the object in the array:

In [33]:
arr.dtype #It will show data type of array element.

dtype('int32')

# Great Job!