### NumPy Indexing and Selection

1. Bracket indexing and selection
2. Broadcasting
3. Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Bracket Indexing and Selection

* The simplest way to pick one or some elements of an array looks very similar to python lists:
* Always index count from the zero.

In [4]:
arr[8] 

8

In [5]:
arr[1:5] 

array([1, 2, 3, 4])

In [6]:
arr[:]   # All elements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Broadcasting

* Numpy arrays differ from a normal Python list because of their ability to broadcast

In [7]:
arr[0:5]=100 # Assign the value to specific indexes range. 

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[1] #print the 1th row.

array([20, 25, 30])

In [15]:
arr_2d[1][0]#print the 1th row 0s element.

20

In [16]:
arr_2d[:2,1:]#print the prevoius of 2th row and 1th after column.

array([[10, 15],
       [25, 30]])

In [17]:
arr_2d[2,:]#Just print the 2nd row.

array([35, 40, 45])

#### Selection

* Let's briefly go over how to use brackets for selection based off of comparison operators.

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr>4

In [21]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
